Setup
jerrymartinszup/YFood pull request #1
Opened 2020-05-29 14:02 UTC by jerrymartinszup

utilizando r2dbc e postgres, feita a modelagem inicial para cadastro de cliente com retorno de seus métodos de pagamento

2020-05-29 19:35 UTC, albertotavareszup requested changes
Oi Jerry, antes de revisar aqui. No cartão para construir as abstrações iniciais e dar carga nos dados, não precisa ainda de parte web. Rola adaptar o código para o cenário? Pq aí a revisão fica mais interessante :).

2020-05-29 20:06 UTC, jerrymartinszup commented
> Oi Jerry, antes de revisar aqui. No cartão para construir as abstrações iniciais e dar carga nos dados, não precisa ainda de parte web. Rola adaptar o código para o cenário? Pq aí a revisão fica mais interessante :).

parte web removida

2020-05-29 23:11 UTC, albertotavareszup approved these changes
Ah, aqui ainda não tem a carga, né? tudo bem. Eu me confundi, perdão :(.

2020-05-29 23:11 UTC, albertotavareszup commented on src/main/java/com/yfood/payments/domain/Customer.java
>      private Set<PaymentTypeEnum> paymentsTypes;
Por curiosidade, pq tem Enum no nome? Para facilitar a busca na ide?

2020-05-29 23:11 UTC, albertotavareszup commented on src/main/java/com/yfood/payments/domain/Customer.java
> +    public Set<PaymentTypeEnum> getPaymentsTypesAccepts() {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Pq temos esse getter?

2020-05-29 23:11 UTC, albertotavareszup commented on src/main/java/com/yfood/payments/domain/Restaurant.java
>      public Set<PaymentTypeEnum> getPaymentsTypesAccepts() {
mesma coisa do de cima :).

2020-05-30 00:41 UTC, jerrymartinszup commented on src/main/java/com/yfood/payments/domain/Customer.java
>      private Set<PaymentTypeEnum> paymentsTypes;
Para facilitar a busca na IDE,  mas costumo também utilizar isto para padronizar, normalmente no domain ficaria CustomerDomain, mas acabei deixando o customer sem domain como sufixo. Posso Remover o Enum do nome ou adicionar Domain como sufixo à classe Customer para padronizar.

2020-05-30 00:43 UTC, jerrymartinszup commented on src/main/java/com/yfood/payments/domain/Customer.java
> +    public Set<PaymentTypeEnum> getPaymentsTypesAccepts() {
não está sendo utilizando agora, mas será utilizado para retornar a lista de tipos de pagamentos de um cliente.

2020-05-30 00:44 UTC, jerrymartinszup commented on src/main/java/com/yfood/payments/domain/Restaurant.java
>      public Set<PaymentTypeEnum> getPaymentsTypesAccepts() {
não está sendo utilizando agora, mas será utilizado para retornar a lista de tipos de pagamentos aceitos por um restaurante.
posso remover este método e o outro mas logo ele precisará ser criado novamente.

2020-05-30 20:42 UTC, merged